version: '3.5'

services:
  ng:
    container_name: nginx
    image: nginx:1.20.2-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /home/ubuntu/SintesisProjects/genesis-pgw/gpgw-angular-integration/dist:/var/www/genesis-site:ro
    ports:
      - "127.0.0.1:80-90:80-90"