version: '3.5'

services:
  ng:
    container_name: nginx
    image: nginx:1.20.2-alpine
    network_mode: host
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - /home/ubuntu/SintesisProjects/genesis-pgw/gpgw-angular-integration/dist:/var/www/genesis-site:ro